### ISSUE TITLE
feat: Debian change packages locking method

### ISSUE THREAD

**Issue by vfricou** [vfricou/ansible_playbook_linux_postinstall#11]
Actually package locking use scripts.  
Perfer to use `dpkg_selection` module as :

```yaml
- name: Hold linux
  dpkg_selections:
    name: linux
    selection: hold
```
